package country

var SurnamesRussia = []string {
	"Abakumov (Абакумов)",
	"Abdulov (Абдулов)",
	"Abramov (Абрамов)",
	"Abramovich (Абрамович)",
	"Avdeyev (Авдеев)",
	"Avdonin (Авдонин)",
	"Averin (Аверин)",
	"Averyanov (Аверьянов)",
	"Avilov (Авилов)",
	"Agapov (Агапов)",
	"Agafonov (Агафонов)",
	"Ageykin (Агейкин)",
	"Agliullin (Аглиуллин)",
	"Adaksin (Адаксин)",
	"Azarov (Азаров)",
	"Akinfeev (Акинфеев)",
	"Aksakov (Аксаков)",
	"Aksenchuk (Аксенчук)",
	"Akhmedov (Ахмедов)",
	"Aksyonov (Аксёнов)",
	"Akulov (Акулов)",
	"Aleyev (Алеев)",
	"Alexandrov (Александров)",
	"Alexeyev (Алексеев)",
	"Alenin (Аленин)",
	"Alekhin (Алехин)",
	"Alyokhin (Алёхин)",
	"Aliyev (Алиев)",
	"Alistratov (Алистратов)",
	"Alliluyev (Аллилуев)",
	"Alogrin (Алогрин)",
	"Amaliyev (Амалиев)",
	"Amelin (Амелин)",
	"Aminev (Аминев)",
	"Ananyev (Ананьев)",
	"Anasenko (Анасенко)",
	"Andreyev (Андреев)",
	"Andreyushkin (Андреюшкин)",
	"Andronikov (Андроников)",
	"Andropov (Андропов)",
	"Andryukhin (Андрюхин)",
	"Anikanov (Аниканов)",
	"Anikin (Аникин)",
	"Anisimov (Анисимов)",
	"Anishin (Анишин)",
	"Ankudinov (Анкудинов)",
	"Annenkov (Анненков)",
	"Annikov (Анников)",
	"Anosov (Аносов)",
	"Anokhin (Анохин)",
	"Anoshkin (Аношкин)",
	"Anrep (Анреп)",
	"Antakov (Антаков)",
	"Antipin (Антипин)",
	"Antipov (Антипов)",
	"Antonov (Антонов)",
	"Antonovich (Антонович)",
	"Anushchenkov (Анущенков)",
	"Apalkov (Апалков)",
	"Aptekar (Аптекарь)",
	"Arefyev (Арефьев)",
	"Arzamastsev (Арзамасцев)",
	"Aristarkhov (Аристархов)",
	"Aristov (Аристов)",
	"Arsenyev (Арсеньев)",
	"Artamonov (Артамонов)",
	"Artemyev (Артемьев)",
	"Artyomov (Артёмов)",
	"Arkhangelsky (Архангельский)",
	"Arshavin (Аршавин)",
	"Aslanov (Асланов)",
	"Aslakhanov (Аслаханов)",
	"Aspidov (Аспидов)",
	"Assonov (Ассонов)",
	"Astankov (Астанков)",
	"Astafyev (Астафьев)",
	"Astakhov (Астахов)",
	"Afanasyev (Афанасьев)",
	"Afonin (Афонин)",
	"Akhremenko (Ахременко)",
	"Ayushiyev (Аюшиев)",
	"Ayushcheglov (Ающеглов)",
	"Babanin (Бабанин)",
	"Babaev (Бабаев)",
	"Babikov (Бабиков)",
	"Babichev (Бабичев)",
	"Babkin (Бабкин)",
	"Baburin (Бабурин)",
	"Babykin (Бабыкин)",
	"Bagrov (Багров)",
	"Bazhanov (Бажанов)",
	"Bazhenov (Баженов)",
	"Bazanov (Базанов)",
	"Bazarov (Базаров)",
	"Bazin (Базин)",
	"Balabanov (Балабанов)",
	"Balakin (Балакин)",
	"Balakirev (Балакирев)",
	"Balandin (Баландин)",
	"Balashov (Балашов)",
	"Baranov (Баранов)",
	"Baranovsky (Барановский)",
	"Baratynsky (Баратынский)",
	"Barbolin (Барболин)",
	"Barinov (Баринов)",
	"Barkov (Барков)",
	"Barsukov (Барсуков)",
	"Baryshev (Барышев)",
	"Baryshnikov (Барышников)",
	"Baskin (Баскин)",
	"Batishchev (Батищев)",
	"Batrutdinov (Батрутдинов)",
	"Bebnev (Бебнев)",
	"Bebchuk (Бебчук)",
	"Bezborodov (Безбородов)",
	"Bezobrazov (Безобразов)",
	"Bezrodny (Безродный)",
	"Bezrukov (Безруков)",
	"Bezukladnikov (Безукладников)",
	"Belevich (Белевич)",
	"Belikov (Беликов)",
	"Belinsky (Белинский)",
	"Belov (Белов)",
	"Beloglazov (Белоглазов)",
	"Belorusov (Белорусов)",
	"Belomestnov (Беломестнов)",
	"Belomestnykh (Беломестных)",
	"Belousov (Белоусов)",
	"Belochkin (Белочкин)",
	"Belyakov (Беляков)",
	"Belyaev (Беляев)",
	"Benediktov (Бенедиктов)",
	"Berezhnoy (Бережной)",
	"Berezin (Березин)",
	"Beriya (Берия)",
	"Bershov (Бершов)",
	"Bespalov (Беспалов)",
	"Bessonov (Бессонов)",
	"Besfamilny (Бесфамильный)",
	"Bekhterev (Бехтерев)",
	"Biryukov (Бирюков)",
	"Blagonravov (Благонравов)",
	"Blazhenov (Блаженов)",
	"Blanter (Блантер)",
	"Blatov (Блатов)",
	"Blinov (Блинов)",
	"Bliznyuk (Близнюк)",
	"Blok (Блок)",
	"Blokov (Блоков)",
	"Blokhin (Блохин)",
	"Blum (Блум)",
	"Bobkov (Бобков)",
	"Bobr (Бобр)",
	"Bobrik (Бобрик)",
	"Bobrinsky (Бобринский)",
	"Bobrov (Бобров)",
	"Bogatyryov (Богатырёв)",
	"Bogachyov (Богачёв)",
	"Bogdanov (Богданов)",
	"Bogolepov (Боголепов)",
	"Bogolyubov (Боголюбов)",
	"Bogolyubsky (Боголюбский)",
	"Bogomazov (Богомазов)",
	"Bogomolov (Богомолов)",
	"Bogrov (Богров)",
	"Bogun (Богун)",
	"Bodrov (Бодров)",
	"Boykov (Бойков)",
	"Boytsov (Бойцов)",
	"Bok (Бок)",
	"Bokaryov (Бокарёв)",
	"Boldyrev (Болдырев)",
	"Bolotnikov (Болотников)",
	"Boltonogov (Болтоногов)",
	"Bolshakov (Большаков)",
	"Bolshov (Большов)",
	"Bondarev (Бондарев)",
	"Bondarchuk (Бондарчук)",
	"Boreyev (Бореев)",
	"Borzilov (Борзилов)",
	"Borisyuk (Борисюк)",
	"Borovkov (Боровков)",
	"Borodin (Бородин)",
	"Bortnik (Бортник)",
	"Bortsov (Борцов)",
	"Bocharov (Бочаров)",
	"Boyarov (Бояров)",
	"Bravikov (Бравиков)",
	"Bragin (Брагин)",
	"Brantov (Брантов)",
	"Brezhnev (Брежнев)",
	"Brusilov (Брусилов)",
	"Bryzgalov (Брызгалов)",
	"Bugayev (Бугаев)",
	"Bugaychuk (Бугайчук)",
	"Bugakov (Бугаков)",
	"Budayev (Будаев)",
	"Budanov (Буданов)",
	"Budnikov (Будников)",
	"Budylin (Будылин)",
	"Buzinsky (Бузинский)",
	"Bukin (Букин)",
	"Bukov (Буков)",
	"Bulgakov (Булгаков)",
	"Bulygin (Булыгин)",
	"Bunin (Бунин)",
	"Burdukovsky (Бурдуковский)",
	"Burkov (Бурков)",
	"Burmakin (Бурмакин)",
	"Burov (Буров)",
	"Burtsov (Бурцов)",
	"Bury (Бурый)",
	"Buryakov (Буряков)",
	"Butusov (Бутусов)",
	"Butylin (Бутылин)",
	"Bukhalo (Бухало)",
	"Bykov (Быков)",
	"Bylinkin (Былинкин)",
	"Bychkov (Бычков)",
	"Vavilov (Вавилов)",
	"Vagin (Вагин)",
	"Varennikov (Варенников)",
	"Varfolomeyev (Варфоломеев)",
	"Vartanov (Вартанов)",
	"Varushkin (Варушкин)",
	"Vasilevsky (Василевский)",
	"Vasilyev (Васильев)",
	"Vasin (Васин)",
	"Vasnev (Васнев)",
	"Vasnetsov (Васнецов)",
	"Vakhrushev (Вахрушев)",
	"Vedeneyev (Веденеев)",
	"Vedenin (Веденин)",
	"Vedernikov (Ведерников)",
	"Venediktov (Венедиктов)",
	"Verenich (Веренич)",
	"Vereshchagin (Верещагин)",
	"Vershinin (Вершинин)",
	"Veselov (Веселов)",
	"Veselovsky (Веселовский)",
	"Vetochkin (Веточкин)",
	"Vetrov (Ветров)",
	"Vinogradov (Виноградов)",
	"Vinokurov (Винокуров)",
	"Vitvinin (Витвинин)",
	"Vikhrov (Вихров)",
	"Vitsin (Вицин)",
	"Vodovatov (Водоватов)",
	"Vodyanov (Водянов)",
	"Volikov (Воликов)",
	"Volkov (Волков)",
	"Volodin (Володин)",
	"Volosenkov (Волосенков)",
	"Voloshin (Волошин)",
	"Volvakov (Вольваков)",
	"Vorobyov (Воробьёв)",
	"Voronin (Воронин)",
	"Voronkov (Воронков)",
	"Voronov (Воронов)",
	"Vorontsov (Воронцов)",
	"Voskoboynikov (Воскобойников)",
	"Voskresensky (Воскресенский)",
	"Votyakov (Вотяков)",
	"Vyrypayev (Вырыпаев)",
	"Vyalitsyn (Вьялицын)",
	"Gavrikov (Гавриков)",
	"Gavrilenkov (Гавриленков)",
	"Gavrilov (Гаврилов)",
	"Gagarin (Гагарин)",
	"Gagolin (Гаголин)",
	"Galdin (Галдин)",
	"Galyorkin (Галёркин)",
	"Galiaskarov (Галиаскаров)",
	"Galkin (Галкин)",
	"Galygin (Галыгин)",
	"Garanin (Гаранин)",
	"Garin (Гарин)",
	"Garifullin (Гарифуллин)",
	"Gachev (Гачев)",
	"Genkin (Генкин)",
	"Gerasimov (Герасимов)",
	"Gilyov (Гилёв)",
	"Glagolev (Глаголев)",
	"Glazkov (Глазков)",
	"Glebov (Глебов)",
	"Glinin (Глинин)",
	"Globa (Глоба)",
	"Glukhov (Глухов)",
	"Govyadinov (Говядинов)",
	"Golov (Голов)",
	"Golovanov (Голованов)",
	"Golovakha (Головаха)",
	"Golovin (Головин)",
	"Golovkin (Головкин)",
	"Golodyayev (Голодяев)",
	"Gololobov (Гололобов)",
	"Golubev (Голубев)",
	"Golubkin (Голубкин)",
	"Golubov (Голубов)",
	"Golubtsov (Голубцов)",
	"Golumbovsky (Голумбовский)",
	"Goncharov (Гончаров)",
	"Gorbachyov (Горбачёв)",
	"Gorbunkov (Горбунков)",
	"Gorbunov (Горбунов)",
	"Gorev (Горев)",
	"Gorelov (Горелов)",
	"Goremykin (Горемыкин)",
	"Gornostayev (Горностаев)",
	"Gorokhov (Горохов)",
	"Gorshkov (Горшков)",
	"Goryunov (Горюнов)",
	"Grankin (Гранкин)",
	"Grafov (Графов)",
	"Grachyov (Грачёв)",
	"Grebenshchikov (Гребенщиков)",
	"Grekov (Греков)",
	"Greshnov (Грешнoв)",
	"Gribanov (Грибанов)",
	"Gribkov (Грибков)",
	"Gribov (Грибов)",
	"Griboyedov (Грибоедов)",
	"Grigoryev (Григорьев)",
	"Grinin (Гринин)",
	"Grishin (Гришин)",
	"Gromov (Громов)",
	"Gruzdev (Груздев)",
	"Gruzinsky (Грузинский)",
	"Grushanin (Грушанин)",
	"Gryaznov (Грязнов)",
	"Gubanov (Губанов)",
	"Gulin (Гулин)",
	"Gunin (Гунин)",
	"Gurkovsky (Гурковский)",
	"Guryev (Гурьев)",
	"Guryanov (Гурьянов)",
	"Gusarov (Гусаров)",
	"Gusev (Гусев)",
	"Gusin (Гусин)",
	"Guslyakov (Гусляков)",
	"Guskov (Гуськов)",
	"Gushchin (Гущин)",
	"Davydkin (Давыдкин)",
	"Davydov (Давыдов)",
	"Datsishin (Дацишин)",
	"Datsyuk (Дацюк)",
	"Dvornikov (Дворников)",
	"Degtyarev (Дегтярёв)",
	"Dedov (Дедов)",
	"Dezhnyov (Дежнёв)",
	"Delov (Делов)",
	"Demenok (Деменок)",
	"Dementyev (Дементьев)",
	"Demidov (Демидов)",
	"Denikin (Деникин)",
	"Denisov (Денисов)",
	"Derzhavin (Державин)",
	"Dernov (Дернов)",
	"Dyogtev (Дёгтев)",
	"Dyomin (Дёмин)",
	"Dmitriyev (Дмитриев)",
	"Dobrolyubov (Добролюбов)",
	"Dobronravov (Добронравов)",
	"Dobrynin (Добрынин)",
	"Dolgorukov (Долгоруков)",
	"Dolzhikov (Должиков)",
	"Domashyov (Домашёв)",
	"Domnin (Домнин)",
	"Dorofeyev (Дорофеев)",
	"Dorokhin (Дорохин)",
	"Dorokhov (Дорохов)",
	"Dostovalov (Достовалов)",
	"Dostoyevsky (Достоевский)",
	"Dragomirov (Драгомиров)",
	"Dragunov (Драгунов)",
	"Dresvyanin (Дресвянин)",
	"Dryomov (Дрёмов)",
	"Druganin (Друганин)",
	"Drugov (Другов)",
	"Dryagin (Дрягин)",
	"Dubinin (Дубинин)",
	"Dubinkin (Дубинкин)",
	"Dubov (Дубов)",
	"Dubolazov (Дуболазов)",
	"Dubrovsky (Дубровский)",
	"Dudin (Дудин)",
	"Dudko (Дудко)",
	"Dudnik (Дудник)",
	"Dultsev (Дульцев)",
	"Dunayevsky (Дунаевский)",
	"Durov (Дуров)",
	"Dykhovichny (Дыховичный)",
	"Dyuzhenkov (Дюженков)",
	"Dyatlov (Дятлов)",
	"Delyanin (Делянин)",
	"Yevdokimov (Евдокимов)",
	"Yevseyev (Евсеев)",
	"Yevstigneyev (Евстигнеев)",
	"Yevtushenkov (Евтушенков)",
	"Yegorov (Егоров)",
	"Yedemsky (Едемский)",
	"Yezhov (Ежов)",
	"Yelagin (Елагин)",
	"Yeleshev (Елешев)",
	"Yelizarov (Елизаров)",
	"Yeliseyev (Елисеев)",
	"Yeltsin (Ельцин)",
	"Yeltsov (Ельцов)",
	"Yelchin (Ельчин)",
	"Yemelin (Емелин)",
	"Yemelyanov (Емельянов)",
	"Yengalychev (Енгалычев)",
	"Yenin (Енин)",
	"Yeremeyev (Еремеев)",
	"Yeryomin (Ерёмин)",
	"Yermakov (Ермаков)",
	"Yermilov (Ермилов)",
	"Yermolayev (Ермолаев)",
	"Yermolov (Ермолoв)",
	"Yermushin (Ермушин)",
	"Yerofeyev (Ерофеев)",
	"Yerokhin (Ерохин)",
	"Yerkhov (Ерхов)",
	"Yershov (Ершов)",
	"Yesaulov (Есаулов)",
	"Yesikov (Есиков)",
	"Yesipov (Есипов)",
	"Yefimov (Ефимов)",
	"Yefremov (Ефремов)",
	"Yeshevsky (Ешевский)",
	"Yozhikov (Ёжиков)",
	"Yozhin (Ёжин)",
	"Yolkin (Ёлкин)",
	"Zhabin (Жабин)",
	"Zharkov (Жарков)",
	"Zharykhin (Жарыхин)",
	"Zhvikov (Жвиков)",
	"Zhdanov (Жданов)",
	"Zheglov (Жеглов)",
	"Zhelezkin (Железкин)",
	"Zheleznov (Железнов)",
	"Zherdev (Жердев)",
	"Zhernakov (Жернаков)",
	"Zhestokov (Жестоков)",
	"Zhyonov (Жёнов)",
	"Zhiglov (Жиглов)",
	"Zhigunov (Жигунов)",
	"Zhidkov (Жидков)",
	"Zhikin (Жикин)",
	"Zhilin (Жилин)",
	"Zhilov (Жилов)",
	"Zhirov (Жиров)",
	"Zholdin (Жолдин)",
	"Zhuk (Жук)",
	"Zhukov (Жуков)",
	"Zhuravlyov (Журавлёв)",
	"Zhurov (Журов)",
	"Zhutov (Жутов)",
	"Zabolotny (Заболотный)",
	"Zavrazhin (Завражин)",
	"Zavrazhnov (Завражнов)",
	"Zavrazhny (Завражный)",
	"Zavrazin (Завразин)",
	"Zavyalov (Завьялов)",
	"Zagorodny (Загородный)",
	"Zadornov (Задорнов)",
	"Zadorozhny (Задорожный)",
	"Zaytsev (Зайцев)",
	"Zakrevsky (Закревский)",
	"Zaporozhets (Запорожец)",
	"Zarubin (Зарубин)",
	"Zaslavsky (Заславский)",
	"Zakhaev (Захаев)",
	"Zakharov (Захаров)",
	"Zakharchenko (Захарченко)",
	"Zakharyin (Захарьин)",
	"Zverev (Зверев)",
	"Zvyagin (Звягин)",
	"Zefirov (Зефиров)",
	"Zyomin (Зёмин)",
	"Zimin (Зимин)",
	"Zimkov (Зимков)",
	"Zimnyakov (Зимняков)",
	"Zinchenko (Зинченко)",
	"Zlobin (Злобин)",
	"Zolin (Золин)",
	"Zolotov (Золотов)",
	"Zonov (Зонов)",
	"Zorin (Зорин)",
	"Zotov (Зотов)",
	"Zubarev (Зубарев)",
	"Zubkov (Зубков)",
	"Zubov (Зубов)",
	"Zuyev (Зуев)",
	"Zuykov (Зуйков)",
	"Zykin (Зыкин)",
	"Zykov (Зыков)",
	"Zyryanov (Зырянов)",
	"Zyuganov (Зюганов)",
	"Ibragimov (Ибрагимов)",
	"Ivakin (Ивакин)",
	"Ivankov (Иванков)",
	"Ivanov (Иванов)",
	"Ivashin (Ивашин)",
	"Ivashov (Ивашов)",
	"Ivkin (Ивкин)",
	"Ivolgin (Иволгин)",
	"Ivchenko (Ивченко)",
	"Ignatkovich (Игнаткович)",
	"Ignatyev (Игнатьев)",
	"Igoshin (Игошин)",
	"Igumnov (Игумнов)",
	"Izhutin (Ижутин)",
	"Izmaylov (Измайлов)",
	"Izyumov (Изюмов)",
	"Ilyin (Ильин)",
	"Ilkun (Илькун)",
	"Ilyushin (Ильюшин)",
	"Ilyasov (Ильясов)",
	"Ilyukhin (Илюхин)",
	"Ilyushin (Илюшин)",
	"Ilyushkin (Илюшкин)",
	"Inozemtsev (Иноземцев)",
	"Ipatyev (Ипатьев)",
	"Isayev (Исаев)",
	"Ismaylov (Исмайлов)",
	"Istomin (Истомин)",
	"Ishutin (Ишутин)",
	"Ishcheglov (Ищеглов)",
	"Ishchegelov (Ищегелов)",
	"Kablukov (Каблуков)",
	"Kaverin (Каверин)",
	"Kadnikov (Кадников)",
	"Kadurin (Кадурин)",
	"Kadtsyn (Кадцын)",
	"Kazak (Казак)",
	"Kazakov (Казаков)",
	"Kazantsev (Казанцев)",
	"Kazankov (Казаньков)",
	"Kazarezov (Казарезов)",
	"Kalagin (Калагин)",
	"Kalashnik (Калашник)",
	"Kalashnikov (Калашников)",
	"Kalganov (Калганов)",
	"Kalinin (Калинин)",
	"Kalugin (Калугин)",
	"Kalyagin (Калягин)",
	"Kamenev (Каменев)",
	"Kamenkovich (Каменкович)",
	"Kamenskikh (Каменских)",
	"Kamkin (Камкин)",
	"Kandinsky (Кандинский)",
	"Kapitsa (Капица)",
	"Kapralov (Капралов)",
	"Kapranov (Капранов)",
	"Kapustin (Капустин)",
	"Karavayev (Караваев)",
	"Karandashov (Карандашов)",
	"Karaulin (Караулин)",
	"Karaulov (Караулов)",
	"Karbainov (Карбаинов)",
	"Kargin (Каргин)",
	"Karev (Карев)",
	"Karetnikov (Каретников)",
	"Kariyev (Кариев)",
	"Karnaukhov (Карнаухов)",
	"Karryev (Каррыев)",
	"Kartashyov (Карташёв)",
	"Kartashov (Карташов)",
	"Karchagin (Карчагин)",
	"Karyavin (Карявин)",
	"Kasaty (Касатый)",
	"Kasyanenko (Касьяненко)",
	"Kasyanov (Касьянов)",
	"Katayev (Катаев)",
	"Katerinochkin (Катериночкин)",
	"Katin (Катин)",
	"Kachusov (Качусов)",
	"Kasharin (Кашарин)",
	"Kashirin (Каширин)",
	"Kashirsky (Каширский)",
	"Kashnikov (Кашников)",
	"Kashuba (Кашуба)",
	"Kvasov (Квасов)",
	"Kedrov (Кедров)",
	"Kilesso (Килессо)",
	"Kipriyanov (Киприянов)",
	"Kireyev (Киреев)",
	"Kirillov (Кириллов)",
	"Kirilov (Кирилов)",
	"Kirsanov (Кирсанов)",
	"Kiryanov (Кирьянов)",
	"Kislukhin (Кислухин)",
	"Klebleyev (Клеблеев)",
	"Klepak (Клепак)",
	"Klepin (Клепин)",
	"Klimov (Климов)",
	"Klimushin (Климушин)",
	"Klimtsov (Климцов)",
	"Klokov (Клоков)",
	"Knyazev (Князев)",
	"Kobyakov (Кобяков)",
	"Kovalevsky (Ковалевский)",
	"Kovalenko (Коваленко)",
	"Kovalyov (Ковалёв)",
	"Kovrov (Ковров)",
	"Kovshutin (Ковшутин)",
	"Kozhurov (Кожуров)",
	"Kozhukhov (Кожухов)",
	"Kozakov (Козаков)",
	"Kozar (Козарь)",
	"Kozlov (Козлов)",
	"Kozlovsky (Козловский)",
	"Kozyrev (Козырев)",
	"Kolesnikov (Колесников)",
	"Kolesov (Колесов)",
	"Kollerov (Коллеров)",
	"Kolobkov (Колобков)",
	"Kolomnikov (Коломников)",
	"Kolontayev (Колонтаев)",
	"Kolosov (Колосов)",
	"Kolupayev (Колупаев)",
	"Koltsov (Кольцов)",
	"Komarov (Комаров)",
	"Komzin (Комзин)",
	"Komissarov (Комиссаров)",
	"Komolov (Комолов)",
	"Kondratyev (Кондратьев)",
	"Kondurov (Кондуров)",
	"Kondyurin (Кондюрин)",
	"Konev (Конев)",
	"Konin (Конин)",
	"Konnikov (Конников)",
	"Konovalov (Коновалов)",
	"Konyakov (Коньяков)",
	"Konyashov (Коняшов)",
	"Kopeykin (Копейкин)",
	"Kopsov (Копсов)",
	"Koptsev (Копцев)",
	"Korablyov (Кораблёв)",
	"Korablin (Кораблин)",
	"Korenev (Коренев)",
	"Korzhakov (Коржаков)",
	"Korzhev (Коржев)",
	"Kornev (Корнев)",
	"Korneyev (Корнеев)",
	"Kornilov (Корнилов)",
	"Korovin (Коровин)",
	"Korolyov (Королёв)",
	"Korotayev (Коротаев)",
	"Koroteyev (Коротеев)",
	"Korotkin (Короткин)",
	"Korotkov (Коротков)",
	"Kortnev (Кортнев)",
	"Korchagin (Корчагин)",
	"Koryavin (Корявин)",
	"Koryavov (Корявов)",
	"Kosarev (Косарев)",
	"Kosarin (Косарин)",
	"Koskov (Косков)",
	"Kosomov (Косомов)",
	"Kosorukov (Косоруков)",
	"Kostin (Костин)",
	"Kostomarov (Костомаров)",
	"Kosyak (Косяк)",
	"Kotov (Котов)",
	"Kochenkov (Коченков)",
	"Koshelev (Кошелев)",
	"Koshechkin (Кошечкин)",
	"Koshkin (Кошкин)",
	"Kravchuk (Кравчук)",
	"Krayev (Краев)",
	"Krayevsky (Краевский)",
	"Kramnik (Крамник)",
	"Krasnov (Краснов)",
	"Krasnopyorov (Краснопёров)",
	"Krasotkin (Красоткин)",
	"Krasavin (Красавин)",
	"Krivkov (Кривков)",
	"Krivov (Кривов)",
	"Krivoukhov (Кривоухов)",
	"Kryuchkov (Крючков)",
	"Kropanin (Кропанин)",
	"Kruglov (Круглов)",
	"Krukov (Круков)",
	"Krupin (Крупин)",
	"Krupich (Крупич)",
	"Krupnov (Крупнов)",
	"Krutikov (Крутиков)",
	"Krutin (Крутин)",
	"Krutov (Крутов)",
	"Krutoy (Крутой)",
	"Kruchinkin (Кручинкин)",
	"Krylov (Крылов)",
	"Krymov (Крымов)",
	"Krysov (Крысов)",
	"Kryukov (Крюков)",
	"Kublanov (Кубланов)",
	"Kubyshkin (Кубышкин)",
	"Kuvayev (Куваев)",
	"Kudashov (Кудашов)",
	"Kudrin (Кудрин)",
	"Kudryavtsev (Кудрявцев)",
	"Kudryashov (Кудряшов)",
	"Kuznetsov (Кузнецов)",
	"Kuzubov (Кузубов)",
	"Kuzkin (Кузькин)",
	"Kuzmin (Кузьмин)",
	"Kuzmich (Кузьмич)",
	"Kuimov (Куимов)",
	"Kuklachyov (Куклачёв)",
	"Kuklev (Куклев)",
	"Kuklin (Куклин)",
	"Kulagin (Кулагин)",
	"Kulakov (Кулаков)",
	"Kulibin (Кулибин)",
	"Kulik (Кулик)",
	"Kulikov (Куликов)",
	"Kuptsov (Купцов)",
	"Kurakin (Куракин)",
	"Kurbatov (Курбатов)",
	"Kurganov (Курганов)",
	"Kurdin (Курдин)",
	"Kurepin (Курепин)",
	"Kuritsyn (Курицын)",
	"Kurochkin (Курочкин)",
	"Kurpatov (Курпатов)",
	"Kurtashkin (Курташкин)",
	"Kurchin (Курчин)",
	"Kustov (Кустов)",
	"Kutepov (Кутепов)",
	"Kutikov (Кутиков)",
	"Kutuzov (Кутузов)",
	"Kutyakov (Кутяков)",
	"Lavrentyev (Лаврентьев)",
	"Lavrov (Лавров)",
	"Lagoshin (Лагошин)",
	"Lagransky (Лагранский)",
	"Lastovka (Ластовка)",
	"Lagutov (Лагутов)",
	"Lazarev (Лазарев)",
	"Lantsov (Ланцов)",
	"Lapayev (Лапаев)",
	"Lapidus (Лапидус)",
	"Lapin (Лапин)",
	"Lapotnikov (Лапотников)",
	"Laptev (Лаптев)",
	"Lapunov (Лапунов)",
	"Larin (Larin)",
	"Larionov (Ларионов)",
	"Lachinov (Лачинов)",
	"Lachkov (Лачков)",
	"Lebedev (Лебедев)",
	"Lebedinsky (Лебединский)",
	"Lebedintsev (Лебединцев)",
	"Lebed (Лебедь)",
	"Levin (Левин)",
	"Levkin (Левкин)",
	"Ledovskoy (Ледовской)",
	"Lelukh (Лелух)",
	"Lenin (Ленин)",
	"Leonidov (Леонидов)",
	"Leonov (Леонов)",
	"Lepyokhin (Лепёхин)",
	"Lermontov (Лермонтов)",
	"Leskov (Лесков)",
	"Lesnichy (Лесничий)",
	"Letov (Летов)",
	"Leshev (Лешев)",
	"Leshchyov (Лещёв)",
	"Lyovkin (Лёвкин)",
	"Lidin (Лидин)",
	"Lilov (Лилов)",
	"Limonov (Лимонов)",
	"Lipin (Липин)",
	"Lipov (Липов)",
	"Lisitsyn (Лисицын)",
	"Lisov (Лисов)",
	"Listratov (Листратов)",
	"Listunov (Листунов)",
	"Likhachyov (Лихачёв)",
	"Loban (Лобан)",
	"Lobanov (Лобанов)",
	"Lobachevsky (Лобачевский)",
	"Lobachyov (Лобачёв)",
	"Lobov (Лобов)",
	"Lovzansky (Ловзанский)",
	"Loginov (Логинов)",
	"Loginovsky (Логиновский)",
	"Loktev (Локтев)",
	"Loktionov (Локтионов)",
	"Lomovtsev (Ломовцев)",
	"Lomonosov (Ломоносов)",
	"Lomtev (Ломтев)",
	"Lopatin (Лопатин)",
	"Lopukhov (Лопухов)",
	"Losev (Лосев)",
	"Losevsky (Лосевский)",
	"Loskutnikov (Лоскутников)",
	"Loskutov (Лоскутов)",
	"Loshchilov (Лощилов)",
	"Lubashev (Лубашев)",
	"Luzhkov (Лужков)",
	"Lukashenko (Лукашенко)",
	"Lukin (Лукин)",
	"Lukov (Луков)",
	"Lukyanenko (Лукьяненко)",
	"Lukyanov (Лукьянов)",
	"Lyzlov (Лызлов)",
	"Lytkin (Лыткин)",
	"Lvov (Львов)",
	"Lyubimov (Любимов)",
	"Lyubimtsev (Любимцев)",
	"Lyutenkov (Лютенков)",
	"Lyutov (Лютов)",
	"Lyagushkin (Лягушкин)",
	"Lyagushov (Лягушов)",
	"Lyadov (Лядов)",
	"Lyalyushkin (Лялюшкин)",
	"Lyamin (Лямин)",
	"Lyapin (Ляпин)",
	"Lyapunov (Ляпунов)",
	"Mager (Магер)",
	"Magomedov (Магомедов)",
	"Maysak (Майсак)",
	"Makarov (Макаров)",
	"Maklakov (Маклаков)",
	"Maksimov (Максимов)",
	"Maksimushkin (Максимушкин)",
	"Maksudov (Максудов)",
	"Malakhov (Малахов)",
	"Malikov (Маликов)",
	"Malinin (Малинин)",
	"Malinov (Малинов)",
	"Malkin (Малкин)",
	"Malyshev (Малышев)",
	"Malykhin (Малыхин)",
	"Malyugin (Малюгин)",
	"Mamin (Мамин)",
	"Mamonov (Мамонов)",
	"Mamykin (Мамыкин)",
	"Manin (Манин)",
	"Mantorov (Манторов)",
	"Manyakin (Манякин)",
	"Marin (Марин)",
	"Marinin (Маринин)",
	"Marinkin (Маринкин)",
	"Markin (Маркин)",
	"Markov (Марков)",
	"Martyushev (Мартюшев)",
	"Maryin (Марьин)",
	"Maslak (Маслак)",
	"Maslov (Маслов)",
	"Matveyev (Матвеев)",
	"Makhmudov (Махмудов)",
	"Masharin (Машарин)",
	"Mashir (Машир)",
	"Medvedev (Медведев)",
	"Medvedkov (Медведков)",
	"Mednikov (Медников)",
	"Meledin (Меледин)",
	"Melekhov (Мелехов)",
	"Meleshchuk (Мелещук)",
	"Melikov (Меликов)",
	"Melnikov (Мельников)",
	"Menshikov (Меншиков/Меньшиков)",
	"Menshchikov (Менщиков)",
	"Merkulov (Меркулов)",
	"Merkushev (Меркушев)",
	"Mesyats (Месяц)",
	"Mekhantyev (Механтьев)",
	"Meshcheryakov (Мещеряков)",
	"Migunov (Мигунов)",
	"Milyokhin (Милёхин)",
	"Miloradov (Милорадов)",
	"Milov (Милов)",
	"Milyukov (Милюков)",
	"Milyutin (Милютин)",
	"Minayev (Минаев)",
	"Mineyev (Минеев)",
	"Minin (Минин)",
	"Minkin (Минкин)",
	"Minkovsky (Миньковский)",
	"Mirnov (Мирнов)",
	"Mirny (Мирный)",
	"Mirov (Миров)",
	"Mironov (Миронов)",
	"Mirokhin (Мирохин)",
	"Mirsky (Мирский)",
	"Misalov (Мисалов)",
	"Mitin (Митин)",
	"Mitkin (Митькин)",
	"Mitrofanov (Митрофанов)",
	"Mikhaylov (Михайлов)",
	"Mikhalyov (Михалёв)",
	"Mikhalitsin (Михалицин)",
	"Mikhalitsyn (Михалицын)",
	"Mikheyev (Михеев)",
	"Miloslavsky (Милославский)",
	"Mishin (Мишин)",
	"Mishnyov (Мишнёв)",
	"Mishutin (Мишутин)",
	"Mozhayev (Можаев)",
	"Moiseyev (Моисеев)",
	"Molchanov (Молчанов)",
	"Mordvinov (Мордвинов)",
	"Morenov (Моренов)",
	"Morozov (Морозов)",
	"Moroshkin (Морошкин)",
	"Moryakov (Моряков)",
	"Mosalyov (Мосалёв)",
	"Mosin (Мосин)",
	"Moskalyov (Москалёв)",
	"Moskvin (Москвин)",
	"Mosyakov (Мосяков)",
	"Mokhov (Мохов)",
	"Muravyov (Муравьёв)",
	"Muratov (Муратов)",
	"Murogov (Мурогов)",
	"Mukhametshin (Мухаметшин)",
	"Mukhanov (Муханов)",
	"Mukhin (Мухин)",
	"Mukhortov (Мухортов)",
	"Myshelov (Мышелов)",
	"Myshkin (Мышкин)",
	"Myagkov (Мягков)",
	"Myasnikov (Мясников)",
	"Myatlev (Мятлев)",
	"Myaukin (Мяукин)",
	"Nabatov (Набатов)",
	"Nazarov (Назаров)",
	"Nasonov (Насонов)",
	"Naumenko (Науменко)",
	"Naumov (Наумов)",
	"Nevzorov (Невзоров)",
	"Nezhdanov (Нежданов)",
	"Nekrasov (Некрасов)",
	"Nekrestyanov (Некрестьянов)",
	"Nemtsev (Немцев)",
	"Nemtsov (Немцов)",
	"Nenashev (Ненашев)",
	"Nepein (Непеин)",
	"Nesterov (Нестеров)",
	"Nechayev (Нечаев)",
	"Nizamutdinov (Низамутдинов)",
	"Nikitin (Никитин)",
	"Nikiforov (Никифоров)",
	"Nikishin (Никишин)",
	"Nikolayev (Николаев)",
	"Nikonov (Никонов)",
	"Nikulin (Никулин)",
	"Novikov (Новиков)",
	"Novichkov (Новичков)",
	"Novokshonov (Новокшонов)",
	"Novoseltsev (Новосельцев)",
	"Nozdryov (Ноздрёв)",
	"Nozdrin (Ноздрин)",
	"Norin (Норин)",
	"Nosachyov (Носачёв)",
	"Noskov (Носков)",
	"Nosov (Носов)",
	"Nuriyev (Нуриев)",
	"Nurmagomedov (Нурмагомедов)",
	"Obnizov (Обнизов)",
	"Obolensky (Оболенский)",
	"Oborin (Оборин)",
	"Ovechkin (Овечкин)",
	"Ogarkov (Огарков)",
	"Ogievich (Огиевич)",
	"Ogorodnikov (Огородников)",
	"Ogurtsov (Огурцов)",
	"Ozerov (Озеров)",
	"Okulov (Окулов)",
	"Olenev (Оленев)",
	"Olkhovsky (Ольховский)",
	"Omelnitskiy (Омельницкий)",
	"Onegin (Онегин)",
	"Onipchenko (Онипченко)",
	"Opokin (Опокин)",
	"Orlov (Орлов)",
	"Osin (Осин)",
	"Osinov (Осинов)",
	"Osintsev (Осинцев)",
	"Osipov (Осипов)",
	"Osipenkov (Осипенков)",
	"Osminin (Осминин)",
	"Osokin (Осокин)",
	"Osolodkin (Осолодкин)",
	"Ostaltsev (Остальцев)",
	"Ostapyuk (Остапюк)",
	"Ostroverkhov (Островерхов)",
	"Ostrovsky (Островский)",
	"Oshurkov (Ошурков)",
	"Oshchov (Ощов )",
	"Pavlenko (Павленко)",
	"Pavlov (Павлов)",
	"Palyulin (Палюлин)",
	"Panarin (Панарин)",
	"Panin (Панин)",
	"Pankin (Панкин)",
	"Pankov (Панков)",
	"Pankratov (Панкратов)",
	"Panfilov (Панфилов)",
	"Pankiv (Панькив)",
	"Papanov (Папанов)",
	"Paramonov (Парамонов)",
	"Parshikov (Паршиков)",
	"Parshin (Паршин)",
	"Pasternak (Пастернак)",
	"Pastukh (Пастух)",
	"Paskhin (Пасхин)",
	"Patrushev (Патрушев)",
	"Paulkin (Паулкин)",
	"Pakhomov (Пахомов)",
	"Pashin (Пашин)",
	"Pashkov (Пашков)",
	"Pevtsov (Певцов)",
	"Pelevin (Пелевин)",
	"Pelyovin (Пелёвин)",
	"Penkin (Пенкин)",
	"Pervak (Первак)",
	"Perevalov (Перевалов)",
	"Pereverzev (Переверзев)",
	"Perevyortov (Перевёртов)",
	"Perezhogin (Пережогин)",
	"Perestoronin (Пересторонин)",
	"Perminov (Перминов)",
	"Permyakov (Пермяков)",
	"Perov (Перов)",
	"Perfilyev (Перфильев)",
	"Pestov (Пестов)",
	"Petrenko (Петренко)",
	"Petrov (Петров)",
	"Petrukhin (Петрухин)",
	"Petukhov (Петухов)",
	"Pechkin (Печкин)",
	"Pivovarov (Пивоваров)",
	"Pimenov (Пименов)",
	"Pirogov (Пирогов)",
	"Pirozhkov (Пирожков)",
	"Pichugin (Пичугин)",
	"Pichushkin (Пичушкин)",
	"Pishchalnikov (Пищальников)",
	"Plaksin (Плаксин)",
	"Platonov (Платонов)",
	"Plemyannikov (Племянников)",
	"Plisetsky (Плисецкий)",
	"Pogodin (Погодин)",
	"Pogrebnov (Погребнов)",
	"Poda (Пода)",
	"Podshivalov (Подшивалов)",
	"Pozharsky (Пожарский)",
	"Pozdnyakov (Поздняков)",
	"Pokrovsky (Покровский)",
	"Polivanov (Поливанов)",
	"Polishchuk (Полищук)",
	"Polnaryov (Полнарёв)",
	"Polovtsev (Половцев)",
	"Polotentsev (Полотенцев)",
	"Poltanov (Полтанов)",
	"Poltorak (Полторак)",
	"Polunin (Полунин)",
	"Polushin (Полушин)",
	"Polyakov (Поляков)",
	"Pomelov (Помелов)",
	"Pomelnikov (Помельников)",
	"Ponikarov (Поникаров)",
	"Ponomaryov (Пономарёв)",
	"Ponchikov (Пончиков)",
	"Popov (Попов)",
	"Popyrin (Попырин)",
	"Portnov (Портнов)",
	"Posokhov (Посохов)",
	"Potapov (Потапов)",
	"Potyomkin (Потёмкин)",
	"Prazdnikov (Праздников)",
	"Preobrazhensky (Преображенский)",
	"Pribylov (Прибылов)",
	"Privalov (Привалов)",
	"Prigozhin (Пригожин)",
	"Primakov (Примаков)",
	"Prikhodko (Приходько)",
	"Pronin (Пронин)",
	"Pronichev (Проничев)",
	"Proskurkin (Проскуркин)",
	"Protasov (Протасов)",
	"Prokhorov (Прохоров)",
	"Pugachyov (Пугачёв)",
	"Pugin (Пугин)",
	"Pudin (Пудин)",
	"Pudovkin (Пудовкин)",
	"Puzakov (Пузаков)",
	"Puzanov (Пузанов)",
	"Putilin (Путилин)",
	"Putilov (Путилов)",
	"Putin (Путин)",
	"Putyatin (Путятин)",
	"Pushkaryov (Пушкарёв)",
	"Pushkin (Пушкин)",
	"Pushnoy (Пушной)",
	"Pshenichnikov (Пшеничников)",
	"Pyryev (Пырьев)",
	"Pyanykh (Пьяных)",
	"Pyatosin (Пятосин)",
	"Rabinovich (Рабинович)",
	"Razin (Разин)",
	"Razuvayev (Разуваев)",
	"Ramazanov (Рамазанов)",
	"Raskalov (Раскалов)",
	"Raspopov (Распопов)",
	"Rasputin (Распутин)",
	"Rasskazov (Рассказов)",
	"Rastorguyev (Расторгуев)",
	"Ratkevich (Раткевич)",
	"Rafikov (Рафиков)",
	"Ravenov (Равенов)",
	"Revyagin (Ревягин)",
	"Revyakin (Ревякин)",
	"Reznichenko (Резниченко)",
	"Reznikov (Резников)",
	"Reznov (Резнов)",
	"Remizov (Ремизов)",
	"Repin (Репин)",
	"Retyunskikh (Ретюнских)",
	"Reshetilov (Решетилов)",
	"Reshetnikov (Решетников)",
	"Rzhevsky (Ржевский)",
	"Roborovsky (Роборовский)",
	"Rogachyov (Рогачёв)",
	"Rogov (Рогов)",
	"Rogozin (Рогозин)",
	"Rodzyanko (Родзянко)",
	"Rodin (Родин)",
	"Rodchenko (Родченко)",
	"Rozhkov (Рожков)",
	"Rozanov (Розанов)",
	"Rozovsky (Розовский)",
	"Rokossovsky (Рокоссовский)",
	"Romanov (Романов)",
	"Rostov (Ростов)",
	"Rostovtsev (Ростовцев)",
	"Roshchin (Рощин)",
	"Rubashkin (Рубашкин)",
	"Rudavin (Рудавин)",
	"Rudin (Рудин)",
	"Rudnikov (Рудников)",
	"Rudov (Рудов)",
	"Rumyantsev (Румянцев)",
	"Runov (Рунов)",
	"Rusakov (Русаков)",
	"Rusanov (Русанов)",
	"Rusnak (Руснак)",
	"Russkikh (Русских)",
	"Ruchkin (Ручкин)",
	"Rybakov (Рыбаков)",
	"Rybalkin (Рыбалкин)",
	"Ryzhanov (Рыжанов)",
	"Ryzhikov (Рыжиков)",
	"Ryzhkov (Рыжков)",
	"Ryzhov (Рыжов)",
	"Rykov (Рыков)",
	"Ryndin (Рындин)",
	"Rychenkov (Рыченков)",
	"Ryurikov (Рюриков)",
	"Ryabkin (Рябкин)",
	"Ryabkov (Рябков)",
	"Ryabov (Рябов)",
	"Ryabtsev (Рябцев)",
	"Ryakhin (Ряхин)",
	"Sabantsev (Сабанцев)",
	"Sabitov (Сабитов)",
	"Savasin (Савасин)",
	"Savkin (Савкин)",
	"Savvatimov (Савватимов)",
	"Savvin (Саввин)",
	"Savenkov (Савенков)",
	"Savinkov (Савинков)",
	"Savrasov (Саврасов)",
	"Sagadeyev (Сагадеев)",
	"Sadovsky (Садовский)",
	"Sadykov (Садыков)",
	"Sazonov (Сазонов)",
	"Saitov (Саитов)",
	"Say (Сай)",
	"Salagin (Салагин)",
	"Salimov (Салимов)",
	"Salko (Салко)",
	"Saltanov (Салтанов)",
	"Salkov (Сальков)",
	"Salnikov (Сальников)",
	"Samarin (Самарин)",
	"Samoylov (Самойлов)",
	"Samokhin (Самохин)",
	"Samsonov (Самсонов)",
	"Sannikov (Санников)",
	"Sapalyov (Сапалёв)",
	"Sapogov (Сапогов)",
	"Sapozhnikov (Сапожников)",
	"Saprykin (Сапрыкин)",
	"Sarnychev (Сарнычев)",
	"Safiullin (Сафиуллин)",
	"Safronov (Сафронов)",
	"Sakharov (Сахаров)",
	"Sayankin (Саянкин)",
	"Sayanov (Саянов)",
	"Svalov (Свалов)",
	"Severinov (Северинов)",
	"Severny (Северный)",
	"Severov (Северов)",
	"Sevostyanov (Севостьянов)",
	"Sedelnikov (Седельников)",
	"Sedov (Седов)",
	"Seleznyov (Селезнёв)",
	"Selivanov (Селиванов)",
	"Semerikov (Семериков)",
	"Semyonov (Семёнов)",
	"Semyanin (Семянин)",
	"Senotrusov (Сенотрусов)",
	"Senkin (Сенькин)",
	"Sergeyev (Сергеев)",
	"Serebrov (Серебров)",
	"Serebryakov (Серебряков)",
	"Seryogin (Серёгин)",
	"Serov (Серов)",
	"Serpionov (Серпионов)",
	"Sechenov (Сеченов)",
	"Syomin (Сёмин)",
	"Sivakov (Сиваков)",
	"Sigayev (Сигаев)",
	"Sigalov (Сигалов)",
	"Sigachyov (Сигачёв)",
	"Sidorov (Сидоров)",
	"Sizov (Сизов)",
	"Sizy (Сизый)",
	"Silayev (Силаев)",
	"Silivanov (Силиванов)",
	"Silin (Силин)",
	"Silvestrov (Сильвестров)",
	"Silnov (Сильнов)",
	"Simakin (Симакин)",
	"Simonov (Симонов)",
	"Sitnikov (Ситников)",
	"Siyanin (Сиянин)",
	"Siyanko (Сиянко)",
	"Siyanov (Сиянов)",
	"Siyanovich (Сиянович)",
	"Skvortsov (Скворцов)",
	"Skorobogatov (Скоробогатов)",
	"Skorokhodov (Скороходов)",
	"Skryabin (Скрябин)",
	"Skumin (Скумин)",
	"Skuratov (Скуратов)",
	"Slavsky (Славский)",
	"Slepynin (Слепынин)",
	"Slobozhanin (Слобожанин)",
	"Sluchevsky (Случевский)",
	"Smagin (Смагин)",
	"Smetanin (Сметанин)",
	"Smekhov (Смехов)",
	"Smeshnoy (Смешной)",
	"Smirnitsky (Смирнитский)",
	"Smirnov (Смирнов)",
	"Smolin (Смолин)",
	"Smolyaninov (Смолянинов)",
	"Smotrov (Смотров)",
	"Snatkin (Снаткин)",
	"Snegiryov (Снегирёв)",
	"Snetkov (Снетков)",
	"Sobachkin (Собачкин)",
	"Sobolev (Соболев)",
	"Sobolevsky (Соболевский)",
	"Sobchak (Собчак)",
	"Sokolov (Соколов)",
	"Soldatov (Солдатов)",
	"Solovyov (Соловьёв)",
	"Solodnikov (Солодников)",
	"Solodskikh (Солодских)",
	"Solomakhin (Соломахин)",
	"Solomin (Соломин)",
	"Solomonov (Соломонов)",
	"Somov (Сомов)",
	"Sonin (Сонин)",
	"Sopov (Сопов)",
	"Sorokin (Сорокин)",
	"Spanov (Спанов)",
	"Speransky (Сперанский)",
	"Spravtsev (Справцев)",
	"Stalin (Сталин)",
	"Starikov (Стариков)",
	"Staroverov (Староверов)",
	"Starodubov (Стародубов)",
	"Starodubtsev (Стародубцев)",
	"Startsev (Старцев)",
	"Statnik (Статник)",
	"Steblyov (Стеблёв)",
	"Stezhensky (Стеженский)",
	"Stepanov (Степанов)",
	"Stepankov (Степанков)",
	"Stepashin (Степашин)",
	"Stepnov (Степнов)",
	"Strekalov (Стрекалов)",
	"Strelkov (Стрелков)",
	"Strelnikov (Стрельников)",
	"Streltsov (Стрельцов)",
	"Stroganov (Строганов)",
	"Subbotin (Субботин)",
	"Subotin (Суботин)",
	"Suvorin (Суворин)",
	"Suvorkin (Суворкин)",
	"Suvorov (Суворов)",
	"Sudlenkov (Судленков)",
	"Sungatulin (Сунгатулин)",
	"Sukachyov (Сукачёв)",
	"Sukin (Сукин)",
	"Sukletin (Суклетин)",
	"Sultanov (Султанов)",
	"Suprunov (Супрунов)",
	"Surikov (Суриков)",
	"Surkov (Сурков)",
	"Surnin (Сурнин)",
	"Suslyakov (Сусляков)",
	"Susnin (Суснин)",
	"Sutulin (Сутулин)",
	"Sukhanov (Суханов)",
	"Sukharnikov (Сухарников)",
	"Sukhikh (Сухих)",
	"Sukhorukov (Сухоруков)",
	"Suchkin (Сучкин)",
	"Suchkov (Сучков)",
	"Schastlivtsev (Счастливцев)",
	"Sysoyev (Сысоев)",
	"Sytnikov (Сытников)",
	"Sychyov (Сычёв)",
	"Sychkin (Сычкин)",
	"Syanov (Сьянов)",
	"Tabakov (Табаков)",
	"Talalikhin (Талалихин)",
	"Talanov (Таланов)",
	"Tamarkin (Тамаркин)",
	"Tamakhin (Тамахин)",
	"Tankov (Танков)",
	"Tarasov (Тарасов)",
	"Tarkovsky (Тарковский)",
	"Tarnovetsky (Тарновецкий)",
	"Tatarinov (Татаринов)",
	"Tatarintsev (Татаринцев)",
	"Tatarov (Татаров)",
	"Tataurov (Татауров)",
	"Tattar (Таттар)",
	"Taushev (Таушев)",
	"Tvardovsky (Твардовский)",
	"Telitsyn (Телицын)",
	"Teplov (Теплов)",
	"Teplyashin (Тепляшин)",
	"Terebov (Теребов)",
	"Terekhov (Терехов)",
	"Tereshchenko (Терещенко)",
	"Teryoshin (Терёшин)",
	"Teterev (Тетерев)",
	"Tyomkin (Тёмкин)",
	"Timofeyev (Тимофеев)",
	"Timoshenko (Тимошенко)",
	"Timoshkin (Тимошкин)",
	"Titov (Титов)",
	"Titovich (Титович)",
	"Tikhvinsky (Тихвинский)",
	"Tikhomirov (Тихомиров)",
	"Tikhonenko (Тихоненко)",
	"Tikhonov (Тихонов)",
	"Tikhokhod (Тихоход)",
	"Tkachenko (Ткаченко)",
	"Tkachyov (Ткачёв)",
	"Tokarev (Токарев)",
	"Tokmakov (Токмаков)",
	"Tolbanov (Толбанов)",
	"Tolkachyov (Толкачёв)",
	"Tolmachyov (Толмачёв)",
	"Tolokonsky (Толоконский)",
	"Tolstobrov (Толстобров)",
	"Tolstoy (Толстой)",
	"Tolstokozhev (Толстокожев)",
	"Toporkov (Топорков)",
	"Toporov (Топоров)",
	"Toropov (Торопов)",
	"Torshin (Торшин)",
	"Travkin (Травкин)",
	"Travnikov (Травников)",
	"Trapeznikov (Трапезников)",
	"Trediakovsky (Тредиаковский)",
	"Tretyakov (Третьяков)",
	"Trifonov (Трифонов)",
	"Trofimov (Трофимов)",
	"Trotsky (Троцкий)",
	"Trusov (Трусов)",
	"Trutnev (Трутнев)",
	"Trufanov (Труфанов)",
	"Trukhin (Трухин)",
	"Tryndin (Трындин)",
	"Tumasov (Тумасов)",
	"Tupitsyn (Тупицын)",
	"Tupolev (Туполев)",
	"Turbin (Турбин)",
	"Turgenev (Тургенев)",
	"Turov (Туров)",
	"Tukhachevsky (Тухачевский)",
	"Tychkin (Тычкин)",
	"Tyushnyakov (Тюшняков)",
	"Uvarov (Уваров)",
	"Uglitsky (Углицкий)",
	"Uglichinin (Угличинин)",
	"Uglov (Углов)",
	"Ugolev (Уголев)",
	"Ugolnikov (Угольников)",
	"Udom (Удом)",
	"Ulanov (Уланов)",
	"Ulitsky (Улицкий)",
	"Ulyanin (Ульянин)",
	"Ulyanov (Ульянов)",
	"Ulyashin (Ульяшин)",
	"Umanov (Уманов)",
	"Umsky (Умский)",
	"Ungern (Унгерн)",
	"Unkovsky (Унковский)",
	"Untilov (Унтилов)",
	"Urakov (Ураков)",
	"Uralets (Уралец)",
	"Urbanovsky (Урбановский)",
	"Uritsky (Урицкий)",
	"Urusov (Урусов)",
	"Usatov (Усатов)",
	"Usachyov (Усачёв)",
	"Usenko (Усенко)",
	"Usilov (Усилов)",
	"Usov (Усов)",
	"Uspensky (Успенский)",
	"Ustimovich (Устимович)",
	"Ustinov (Устинов)",
	"Ustyuzhanin (Устюжанин)",
	"Utyosov (Утёсов)",
	"Ukhov (Ухов)",
	"Ukhtomsky (Ухтомский)",
	"Ushakov (Ушаков)",
	"Fadeyev (Фадеев)",
	"Fanin (Фанин)",
	"Fanygin (фаныгин)",
	"Fedin (Федин)",
	"Fedoseyev (Федосеев)",
	"Fedosov (Федосов)",
	"Fedotov (Федотов)",
	"Fedulov (Федулов)",
	"Fedchenkov (Федченков)",
	"Fenenko (Фененко)",
	"Fetisov (Фетисов)",
	"Fyodorov (Фёдоров)",
	"Filatov (Филатов)",
	"Filenkov (Филенков)",
	"Filimonov (Филимонов)",
	"Filipov (Филипов)",
	"Filippov (Филиппов)",
	"Filchenkov (Фильченков)",
	"Firsov (Фирсов)",
	"Flyorov (Флёров)",
	"Fokin (Фокин)",
	"Fomenkov (Фоменков)",
	"Fomin (Фомин)",
	"Fomichyov (Фомичёв)",
	"Fonvizin (Фонвизин)",
	"Foroponov (Форопонов)",
	"Franko (Франко)",
	"Frantsev (Францев)",
	"Frolov (Фролов)",
	"Fukin (Фукин)",
	"Furmanov (Фурманов)",
	"Fynyov (Фыныов)",
	"Khabalov (Хабалов)",
	"Khabarov (Хабаров)",
	"Khabensky (Хабенский)",
	"Khalipov (Халипов)",
	"Khalturin (Халтурин)",
	"Khamidullin (Хамидуллин)",
	"Khanipov (Ханипов)",
	"Khantsev (Ханцев)",
	"Kharitonov (Харитонов)",
	"Kharlamov (Харламов)",
	"Kharmats (Хармац)",
	"Khvostovsky (Хвостовский)",
	"Khigir (Хигир)",
	"Khlebnikov (Хлебников)",
	"Khlebov (Хлебов)",
	"Khloponin (Хлопонин)",
	"Khmelnov (Хмельнов)",
	"Khovansky (Хованский)",
	"Kholodnaya (Холодная)",
	"Kholodov (Холодов)",
	"Khomkolov (Хомколов)",
	"Khorkov (Хорьков)",
	"Khomorkov (Хоморков)",
	"Khokhlachyov (Хохлачёв)",
	"Khramov (Храмов)",
	"Khrebtov (Хребтов)",
	"Khromov (Хромов)",
	"Khrushchev (Хрущёв)",
	"Khudovekov (Худовеков)",
	"Khudyakov (Худяков)",
	"Khurtin (Хуртин)",
	"Tsaplin (Цаплин)",
	"Tsaregorodtsev (Царегородцев)",
	"Tsaryov (Царёв)",
	"Tsaritsyn (Царицын)",
	"Tsvetayev (Цветаев)",
	"Tsvetkov (Цветков)",
	"Tsvetnov (Цветнов)",
	"Tsvilenev (Цвиленев)",
	"Tseytlin (Цейтлин)",
	"Tselikovsky (Целиковский)",
	"Tsertelev (Церетели)",
	"Tsekhanovetsky (Цехановецкий)",
	"Tsigler (Циглер)",
	"Tsimmerman (Циммерман)",
	"Tsiolkovsky (Циолковский)",
	"Tsirinsky (Циринский)",
	"Tsirkunov (Циркунов)",
	"Tsiryulnikov (Цирюльников)",
	"Tsitsianov (Цицианов)",
	"Tsukanov (Цуканов)",
	"Tsulukidze (Цулукидзе)",
	"Tsyganov (Цыганов)",
	"Tsyzyrev (Цызырев)",
	"Tsyukov (Тсыыуков)",
	"Chaadayev (Чаадаев)",
	"Chadov (Чадов)",
	"Chazov (Чазов)",
	"Chayka (Чайка)",
	"Chaykovsky (Чайковский)",
	"Chaly (Чалый)",
	"Chapayev (Чапаев)",
	"Charkov (Чарков)",
	"Chebotaryov (Чеботарёв)",
	"Chebykin (Чебыкин)",
	"Chekmaryov (Чекмарёв)",
	"Chekudayev (Чекудаев)",
	"Chelomey (Челомей)",
	"Chelpanov (Челпанов)",
	"Chemeris (Чемерис)",
	"Chendev (Чендев)",
	"Chepurin (Чепурин)",
	"Chervyakov (Червяков)",
	"Cherenchikov (Черенчиков)",
	"Cherepanov (Черепанов)",
	"Cherkasov (Черкасов)",
	"Cherkashin (Черкашин)",
	"Chernakov (Чернаков)",
	"Chernukhin (Чернухин)",
	"Chernetsky (Чернецкий)",
	"Chernikov (Черников)",
	"Chernobrovin (Чернобровин)",
	"Chernov (Чернов)",
	"Chernomyrdin (Черномырдин)",
	"Chernykh (Черных)",
	"Chernyshyov (Чернышёв)",
	"Chernyavsky (Чернявский)",
	"Chesnokov (Чесноков)",
	"Chekhov (Чехов)",
	"Chigrakov (Чиграков)",
	"Chizhikov (Чижиков)",
	"Chilayev (Чилаев)",
	"Chistyakov (Чистяков)",
	"Chichikov (Чичиков)",
	"Chichkanov (Чичканов)",
	"Chkalov (Чкалов)",
	"Chmykhov (Чмыхов)",
	"Chubarov (Чубаров)",
	"Chugunov (Чугунов)",
	"Chudov (Чудов)",
	"Chuzhinov (Чужинов)",
	"Chukreyev (Чукреев)",
	"Chumakov (Чумаков)",
	"Chupalov (Чупалов)",
	"Chupakhin (Чупахин)",
	"Chupov (Чупов)",
	"Chuprakov (Чупраков)",
	"Chuprin (Чуприн)",
	"Chuprov (Чупров)",
	"Churkin (Чуркин)",
	"Chuchanov (Чучанов)",
	"Shabalin (Шабалин)",
	"Shabunin (Шабунин)",
	"Shaburov (Шабуров)",
	"Shakmakov (Шакмаков)",
	"Shalyapin (Шаляпин)",
	"Shapovalov (Шаповалов)",
	"Shaposhnikov (Шапошников)",
	"Sharapov (Шарапов)",
	"Sharov (Шаров)",
	"Sharonov (Шаронов)",
	"Sharshin (Шаршин)",
	"Shastin (Шастин)",
	"Shatalov (Шаталов)",
	"Shashlov (Шашлов)",
	"Shvedov (Шведов)",
	"Shvernik (Шверник)",
	"Shevelyov (Шевелёв)",
	"Shelagin (Шелагин)",
	"Shelepov (Шелепов)",
	"Shelomov (Шеломов)",
	"Shelyapin (Шеляпин)",
	"Shepovalov (Шеповалов)",
	"Sheremetyev (Шереметьев)",
	"Sherstov (Шерстов)",
	"Shibalov (Шибалов)",
	"Shigayev (Шигаев)",
	"Shigin (Шигин)",
	"Shikalov (Шикалов)",
	"Shinsky (Шинский)",
	"Shirinov (Ширинов)",
	"Shirmanov (Ширманов)",
	"Shirokov (Широков)",
	"Shikhov (Шихов)",
	"Shikhranov (Шихранов)",
	"Shishkanov (Шишканов)",
	"Shishkin (Шишкин)",
	"Shishko (Шишко)",
	"Shishlov (Шишлов)",
	"Shishov (Шишов)",
	"Shkuratov (Шкуратов)",
	"Shkut (Шкут)",
	"Shlykov (Шлыков)",
	"Shmagin (Шмагин)",
	"Shmakov (Шмаков)",
	"Shmelyov (Шмелёв)",
	"Shpak (Шпак)",
	"Shpikalov (Шпикалов)",
	"Shubin (Шубин)",
	"Shubkin (Шубкин)",
	"Shuvalov (Шувалов)",
	"Shuysky (Шуйский)",
	"Shukov (Шуков)",
	"Shukshin (Шукшин)",
	"Shulyov (Шулёв)",
	"Shulga (Шульга)",
	"Shulgin (Шульгин)",
	"Shuldeshov (Шульдешов)",
	"Shults (Шульц)",
	"Shurupov (Шурупов)",
	"Shurshalin (Шуршалин)",
	"Shurygin (Шурыгин)",
	"Shukhov (Шухов)",
	"Shchavelsky (Щавельский)",
	"Shchavlev (Щавлев)",
	"Shchegelsky (Щегельский)",
	"Shcheglov (Щеглов)",
	"Shchegolev (Щеголев)",
	"Shchegolikhin (Щеголихин)",
	"Shchegolyayev (Щеголяев)",
	"Shchedrin (Щедрин)",
	"Shchedrov (Щедров)",
	"Shchekochikhin (Щекочихин)",
	"Shchepkin (Щепкин)",
	"Shcherbakov (Щербаков)",
	"Shcherbatykh (Щербатых)",
	"Shcherbina (Щербина)",
	"Shchetinin (Щетинин)",
	"Shchetkin (Щеткин)",
	"Shchyotkin (Щёткин)",
	"Shchukin (Щукин)",
	"Shchurov (Щуров)",
	"Eybozhenko (Эйбоженко)",
	"Ekel (Экель)",
	"Elembayev (Элембаев)",
	"Elkin (Элькин)",
	"Elmpt (Эльмпт)",
	"Emin (Эмин)",
	"Emsky (Эмский)",
	"Engelgardt (Энгельгардт)",
	"Engovatov (Энговатов)",
	"Entin (Энтин)",
	"Epinger (Эпингер)",
	"Erdeli (Эрдели)",
	"Eristov (Эристов)",
	"Essen (Эссен)",
	"Etush (Этуш)",
	"Yubkin (Юбкин)",
	"Yugov (Югов)",
	"Yudachyov (Юдачёв)",
	"Yudashkin (Юдашкин)",
	"Yudin (Юдин)",
	"Yuditsky (Юдицкий)",
	"Yumatov (Юматов)",
	"Yumashev (Юмашев)",
	"Yunge (Юнге)",
	"Yunevich (Юневич)",
	"Yunkin (Юнкин)",
	"Yurasov (Юрасов)",
	"Yurenev (Юренев)",
	"Yurin (Юрин)",
	"Yurkov (Юрков)",
	"Yurlov (Юрлов)",
	"Yurnayev (Юрнаев)",
	"Yuryev (Юрьев)",
	"Yusupov (Юсупов)",
	"Yuferev (Юферев)",
	"Yukhantsev (Юханцев)",
	"Yushakov (Юшаков)",
	"Yushkov (Юшков)",
	"Yushkivyin (Юшкивыин)",
}

var FemaleFirstNamesRussia = []string {
	"Agrippina",
	"Albina",
	"Alevtina",
	"Alexandra",
	"Alina",
	"Alisa",
	"Alyona",
	"Alla",
	"Anastasia",
	"Anfisa",
	"Anisya",
	"Anna",
	"Anshelika",
	"Antonina",
	"Arina",
	"Asya",
	"Avrora",
	"Avdotya",
	"Daria",
	"Diana",
	"Dina",
	"Edita",
	"Eleonora",
	"Elvira",
	"Emma",
	"Evelina",
	"Faina",
	"Galina",
	"Glafira",
	"Inga",
	"Inna",
	"Irina",
	"Jana",
	"Kapitolina",
	"Kira",
	"Klara",
	"Klavdia",
	"Kristina",
	"Lada",
	"Larisa",
	"Lidiya",
	"Liliya",
	"Ludmila",
	"Lyubov",
	"Maya",
	"Marfa",
	"Margarita",
	"Maria",
	"Marina",
	"Marta",
	"Matryona",
	"Milyena",
	"Nadeshda",
	"Natalya",
	"Nina",
	"Nonna",
	"Nymphadora",
	"Olga",
	"Olesya",
	"Olympiada",
	"Oxana",
	"Pelageya",
	"Polina",
	"Praskovya",
	"Raisa",
	"Rimma",
	"Rosa",
	"Ruslana",
	"Shanna",
	"Serafima",
	"Sofia",
	"Stella",
	"Svetlana",
	"Taisiya",
	"Tamara",
	"Tatiana",
	"Ulyana",
	"Valentina",
	"Valeria",
	"Varvara",
	"Vasilisa",
	"Vera",
	"Veronika",
	"Viktoria",
	"Violetta",
	"Xenia",
	"Yekaterina",
	"Yelena",
	"Yelisaveta",
	"Yeva",
	"Yevdokiya",
	"Yevgeniya",
	"Yevfrosinya",
	"Yulia",
	"Zinaida",
	"Zoya",
}

var MaleFirstNamesRussia = []string{
	"Abram",
	"Alexander",
	"Alexei",
	"Albert",
	"Anatoly",
	"Andrei",
	"Anton",
	"Arkady",
	"Arseny",
	"Artyom",
	"Artur",
	"Afanasy",
	"Bogdan",
	"Boris",
	"Vadim",
	"Valentin",
	"Valery",
	"Vasily",
	"Veniamin",
	"Viktor",
	"Vitaly",
	"Vlad",
	"Vladimir",
	"Vladislav",
	"Vsevolod",
	"Vyacheslav",
	"Gavriil",
	"Garry",
	"Gennady",
	"Georgy",
	"Gerasim",
	"German",
	"Gleb",
	"Grigory",
	"David",
	"Daniil",
	"Denis",
	"Dmitry",
	"Evgeny",
	"Yegor",
	"Yefim",
	"Zakhar",
	"Ivan",
	"Ignat",
	"Igor",
	"Illarion",
	"Ilia",
	"Immanuil",
	"Iosif",
	"Kirill",
	"Konstantin",
	"Lev",
	"Leonid",
	"Makar",
	"Maxim",
	"Marat",
	"Mark",
	"Matvei",
	"Mikhail",
	"Nestor",
	"Nikita",
	"Nikolay",
	"Oleg",
	"Pavel",
	"Pyotr",
	"Robert",
	"Rodion",
	"Roman",
	"Rostislav",
	"Ruslan",
	"Semyon",
	"Sergei",
	"Spartak",
	"Stanislav",
	"Stepan",
	"Taras",
	"Timofei",
	"Timur",
	"Trofim",
	"Eduard",
	"Erik",
	"Yulian",
	"Yury",
	"Yakov",
	"Yaroslav",
}